### PR TITLE
line highlight

### PR DESCRIPTION
**Pull request by yujinyan**
## issue:

image

On mobile devices, the line highlight does not fill overflowing parent's full width, leaving an ugly gap when scrolled to the left.

The issue is present on this page:
https://blog-git-line-highlight.yujinyan.vercel.app/posts/understanding-kotlin-suspend-functions/

### CODE REVIEW

**Comment by koallencheng** [comment]
image

`code`标签可以设置成`display: inline-block`

**Comment by yujinyan** [comment]
改了下发现好像有些 code block 撑不满

image

**Comment by yujinyan** [comment]
好像再加个 `min-width: 100%` 就可以了：
```css
.gatsby-highlight pre > code {
  display: inline-block;
  min-width: 100%;
}
```

**Comment by yujinyan** [comment]
感觉很完美啦，感谢 @koallencheng 😁

**Pull request merged**
